#!/usr/bin/env zsh

antidote_dir="$HOME/.antidote"
[[ -d $antidote_dir ]] ||
  git clone https://github.com/mattmc3/antidote "$antidote_dir"

export PATH="/opt/homebrew/opt/llvm/bin:$PATH"

source $antidote_dir/antidote.zsh
antidote load

bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

eval "$(zoxide init zsh --cmd cd)"
eval "$(starship init zsh)"

if [[ -d "$ZDOTDIR/local" ]]; then
  for file in "$ZDOTDIR/local"/*.zsh; do
    [[ -e "$file" ]] && source "$file"
  done
fi
