return {
	{
		"nvim-treesitter/nvim-treesitter",
		branch = "master",
		event = { "BufReadPost", "BufNewFile", "BufWritePre", "VeryLazy" },
		build = ":TSUpdate",
		main = "nvim-treesitter.configs",
		opts = {
			ensure_installed = {
				"astro",
				"bash",
				"c",
				"css",
				"diff",
				"dockerfile",
				"gitignore",
				"go",
				"gomod",
				"gosum",
				"hcl",
				"html",
				"javascript",
				"json",
				"jsonc",
				"just",
				"lua",
				"luadoc",
				"markdown",
				"markdown_inline",
				"python",
				"query",
				"regex",
				"sql",
				"svelte",
				"terraform",
				"tsx",
				"typescript",
				"vim",
				"vimdoc",
			},
			auto_install = true,
			highlight = {
				enable = true,
				additional_vim_regex_highlighting = false,
			},
			incremental_selection = {
				enable = true,
				keymaps = {
					init_selection = "gnn",
					node_incremental = "grn",
					scope_incremental = "grc",
					node_decremental = "grm",
				},
			},
			indent = { enable = true },
			modules = {},
			sync_install = false,
			ignore_install = {},
		},
	},
}
