require("mini.comment").setup()
require("mini.completion").setup()
require("mini.cursorword").setup()
require("mini.icons").setup()
require("mini.pairs").setup()
require("mini.starter").setup()
require("mini.statusline").setup()
require("mini.ai").setup()
